apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit.fullname" . }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "settings/conf.d/*.yml").AsConfig | indent 2 }}